services:
   frontend:
    image: adamtuska/jobtracker-frontend:latest

    container_name: jobtracker-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - ix-postgres_default

networks:
  ix-postgres_default: